name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  grpc: ^4.0.4
  icons_launcher: ^3.0.1
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    web:
      enable: true
    macos:
      enable: true
    linux:
      enable: true
    windows:
      enable: true


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

